# Generated by Django 3.2.7 on 2021-10-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('explorer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('date_of_birth', models.DateField(null=True)),
                ('bio', models.CharField(blank=True, max_length=140, null=True)),
                ('profile_pic', models.ImageField(upload_to='post_images')),
                ('coins', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=100)),
                ('followings', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('total_images', models.IntegerField(default=0)),
                ('total_videos', models.IntegerField(default=0)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer_app.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer_app.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer_app.state')),
            ],
        ),
    ]
