# Generated by Django 3.1 on 2021-12-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='app_images')),
                ('app_opener_gif', models.ImageField(blank=True, null=True, upload_to='app_images')),
                ('app_font_style', models.CharField(blank=True, max_length=255, null=True)),
                ('app_main_color', models.CharField(blank=True, max_length=255, null=True)),
                ('app_slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('app_welcome_text', models.CharField(blank=True, max_length=255, null=True)),
                ('app_tips_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
